language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: M6Vb1ngkJyg4DjMnM8eLnKT4NBOzlQPTwEzOwmOolJrMfKm7my/sSaDBnVzaCk39kgrMqPuz2/jgzCQ4rcU8jpjvcYkDliR281f/yB1L98HOViwXK09jWlKUOBvy92AuuSaQyGDI8oo1EDPSzlrXN/yjjeQN9NaZmgLCY7jCn8a7o6j1G4KvXntT79sY4Z5K/oUMwVRGsB3LxYQu3/RqZhpnLbi5WP4Vc7/XY6jwyK3SO8bXJKVRHhNoiD14T51QpkDj/Cz8gwCOPkC4q1DshvmlHY9rPrW+BZrCTD8q82bNtUWSgmLLtIUarLAqUYAH99FBseSHisluAfYZAIDmvOiKtj/11iLIQ63RzBekmHsSwPmSfqLGeTWX4iwuJfIaXYXfHL8w21IlK01aq5GiYP+ywXWp1/3zCoAharrmmbf4vsl5e2DN7s/B5WIM7TTNuxE3LqVRTfaUc7xfFlv4eJGD2rMqlk4grsXPHn9XQYu/nwehqNX9w8NPuZXIYTkDgU0l+Vo3atQBSu7lrujc9OtzuAJHbCI1+TrXRKVHXIGNIovvtUnI4x//bJqwOc8gaV+wJTLG/bjrq+/lUROshpj5AfB6ZYfr2tajYMCg6dMU5z6l7RGo19o+rhAbFsr86FgTpe0ZvHkYqnC9etfsVNzEy+oLF5Vo6UiIny2775Y=
  app: 531-progression-tracker
  on:
    repo: aaltamirano1/531-progression-tracker
