language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 0bae0f8b-4c66-491e-9f6e-d3ef76a7f0a0
  app: 531-progression-tracker
  on:
    repo: aaltamirano1/531-progression-tracker
