language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: Ar1/RDFW98PkZ3A1FxPieJSM11SIWSXI3MMuG7iSUEkHOjqWiXScRs0LI9XxY3Rq1BpbUmnfYjiqrOja9zeEBEFgrgLmwO0SGD5PkO6EoNV+avhMHduWjZn38YGdh7t8OJe4clXZlsSSKp2qgykTaIT/qgpIqNjor+fX//gwWVQ6iHIKXb3v0XcUsH5TdhzRioGFfBPfYN7QBU23pVRBAF1SMtuEXcmKkXcdx3MUbszRiX0evSN9qVtz0iUX17tMVh//T+eki555Q+YEjq1MMk24Yhw7shCQp1k8DjVFc74LPiG7/QJSngEntB8o+Gwgu6eWdYQYTqfZ5Hh6q4EtvQ/tOTtPdTS3/ci6d2gBOTjlb64CV9v2OgP9vVeEvOo9hT6hABUQRt33lhfD73e/0oHp3X9bLhqokGfGOwXf5YjWhqS2ot5mI9z7adlJizT9q/wrbEFUHuh+CjkdhnYSk3Z4mshcBCt7WaScKbcR3cLPX/f/WAop6zDoKAQurYAwsRKejb3oBf7Rjaz7bncbDXVxZvCIgcWXsbKWDVWIu17b24xBQmQCVns7T+wkpJf/MZVTrMQZZ3NW6KFMgu/NgruWE/9FsNQWFKmFdYKtKWSrybwjJqwg3AZ3wPZvvzJIxdS5rkh1uUBsiCCGnd+noR7wdiVNpzJMGWpQuRk56RQ=
  app: 531-progression-tracker
  on:
    repo: aaltamirano1/531-progression-tracker
