language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 2abf1fde-0b6d-49b0-a8aa-c5916f05c0e8
  app: the-531-progression-tracker
  on:
    repo: aaltamirano1/531-progression-tracker
